spring.application.name=fraud-service

server.port=9082

#sql

spring.datasource.url=jdbc:postgresql://localhost:5432/frauddb
spring.datasource.username=postgres
spring.datasource.password=908419
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true