spring.application.name=payment-gateway
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=9080

#Stripe API key
stripe.secret.key=${API_KEY}

# Kafka Producer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer